### PR TITLE
Added some Angular and competitive programming resources

### PR DESCRIPTION
**Pull request by rohitkrishna094**
Added some angular tutorials(udemy) and some sample projects' link. Also added some interesting competitive programming websites.

### CODE REVIEW

**Comment by rohitkrishna094** [comment]
Are these conflicts because of me? I dont see any filename issue?

**Comment by Contrevien** [comment]
The filename has been changed from **new-contributors.md** to **CONTRIBUTORS.md**. Kindly update your PR to match this change and I will merge it. Thank you!

**Comment by dipakkr** [comment]
> Are these conflicts because of me? I dont see any filename issue?

Please update your branch from the remote to get latest changes

**Comment by dipakkr** [comment]
@rohitkrishna094 if you wish you can add your LinkedIn profile too, you can connect with lots of people over here. Thanks !! Meging this for now, if you wish you can edit your details later.

**Pull request merged**
