### PR TITLE
Update hackathons with dates

### LINKED ISSUE #807: Suggestion: Organise the list of global hackathons in chronological order
It's easier to reference them if they are in chronological order or alphabetical.

### PR DESCRIPTION
**Pull request by JukieWalsh**
Not sorted and will likely add additional commits to remove events that have ended or have retired pages. 
WIP but will fix #807

### CODE REVIEW

**Comment by JukieWalsh** [comment]
Should I remove the dead/ended events? I'm sure some will have 2019 versions so it's probably best to leave them for visibility.

**Comment by JukieWalsh** [comment]
Will do, I'll update now.

**Comment by Contrevien** [comment]
Go ahead

**Comment by JukieWalsh** [comment]
added the new ones, but it won't display correctly. Does anything jump out at you in the commit?

**Comment by JukieWalsh** [comment]
I left out the column header... good to go now.

**Pull request merged**
