### PR TITLE
Selenium | MongoDB Python | Mysql Python resources added

### PR DESCRIPTION
**Pull request by shauryauppal**

### CODE REVIEW

**Comment by dipakkr** [comment]
Hey please make an issue before PR, it will help us tracking the issues solved.

**Comment by shauryauppal** [comment]
Issue for?

**Comment by shauryauppal** [comment]
Just added three issues.

**Comment by dipakkr** [comment]
For the topic you are sending the  PR. 

It will help us track how many and which resources has been added. 

Like here you can create "Add selenium mongo db MySQL tutorial" then send the PR and reference it in the issue.

**Comment by dipakkr** [comment]
Yes, great, now when you reference the PR number in issue. It will reflect here. 

Your PR has solved which issue.

**Pull request merged**
