### PR TITLE
Typo fixed

### PR DESCRIPTION
**Pull request by jibin2706**
Linking was not working previously to 'Student Benefits and Packs'

### CODE REVIEW

**Comment by dipakkr** [comment]
@jibin2706 pls don't change all the file. While fixing issue make sure you change section in which you are working on. Your changes showing 506 deletions. please update the PR by making only required changes.

Thanks for your contribution !!

**Comment by jibin2706** [comment]
Why is it coming like that? I only changed one line

**Comment by dipakkr** [comment]
@jibin2706 now it's good. Thanks for your contribution.

**Comment by jibin2706** [comment]
I think it was because of the line endings.
I changed it to LF.

**Pull request merged**
