### PR TITLE
Frontend and backend projects

### PR DESCRIPTION
**Pull request by rozig**
Added few projects for #104 and #105

### CODE REVIEW

**Comment by dipakkr** [comment]
@rozig no, it doesn't need to be a tutorial.  Even the technology doesn't matter. But, I appreciate if you will add projects on new technologies.

**Comment by dipakkr** [comment]
@Contrevien pls review the project link and code quality. Also, add tag "Beginner", "Moderate", "Expert" if possible.

**Comment by rozig** [comment]
> @rozig no, it doesn't need to be a tutorial. Even the technology doesn't matter. But, I appreciate if you will add projects on new technologies.

Can you see my last commit? If you want, I can add both tutorial links and repo links

**Comment by Contrevien** [comment]
@rozig Thnak you for your contribution, I'll be accepting _these_ projects.

**Pull request merged**
