### PR TITLE
Development

### PR DESCRIPTION
**Pull request by PratyushaThumiki**
type:docs
Updated the dates and links for various conferences and also rectified some of the links which were not working.
Resolves: #9

### CODE REVIEW

**Comment by PratyushaThumiki** [comment]
Could you please elaborate

**Comment by dipakkr** [comment]
@PratyushaThumiki you were supposed to update conference section as stated in #9 in **README.md** file. But you changed **How-to-contribute.md** file.

I think you misunderstood **How-to-Contribute** guidelines, that is only for absolute beginner to learn how to make PR in an open source repository.

**Comment by dipakkr** [comment]
@PratyushaThumiki still not correct. You have not pulled the updated content from repo yet. Closing this PR. First pull the repo from remote,  add your changes and open another PR.

**Comment by PratyushaThumiki** [comment]
type:docs
I have changed the required files and I apologize for the inconvenience. 
Resolves: #9

**Comment by dipakkr** [comment]
@PratyushaThumiki But due to your previous commits, previous files has also changed. Please make a fresh PR.

**Pull request closed without merging**
