### PR TITLE
Added social media platforms for developers

### PR DESCRIPTION
**Pull request by Ishaan28malik**
## Describe your changes

- Delete this line and write here.

## What did you Change ? 

- Delete this line and write here.

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
ok

**Comment by Ishaan28malik** [comment]
@dipakkr what else can i work upon ?

**Comment by dipakkr** [comment]
> @dipakkr what else can i work upon ?

@Ishaan28malik CLanguageCheaySheet.md Keyword section has wrong formatting. You can make that section more pretty by adding keyword in table. 4x4 table would be good

**Comment by Ishaan28malik** [comment]
@dipakkr I did it pls chk

**Pull request closed without merging**
