### PR TITLE
Add Ruby methods cheatsheet

### PR DESCRIPTION
**Pull request by linda-lai**
## Describe your changes

- Delete this line and write here.

### CODE REVIEW

**Comment by dipakkr** [comment]
@linda-lai thanks for contribution !! please consider adding your name to CONTRIBUTOR.md file.

**Comment by dipakkr** [comment]
This cheat sheet looks good. But, confirm me once that it is your content and not copied from another open source repository to avoid any credit conflicts in future. @linda-lai

**Comment by linda-lai** [comment]
Hi!

Yes, this is a resource I put together in Markdown - just a little reference sheet I updated as I went along, pulled from a few different sources while studying Ruby at my coding bootcamp :)

I'll also add myself to contributors do - this has been a great way to get more comfy with GitHub.

**Comment by dipakkr** [comment]
@linda-lai thanks for the update !! I see you are already added at number 20, as I think have earlier contributed to this repo.

**Pull request merged**
