### PR TITLE
Updated the git and github section with the tutorial link

### PR DESCRIPTION
**Pull request by richa031**

### CODE REVIEW

**Comment by richa031** [comment]
please check I think i did something wrong

**Comment by dipakkr** [comment]
Yeah !! You didn't pull the latest Changes from this repo. That is why it's reflecting old format.

First you have to pull from the master branch and then add you changes

**Comment by dipakkr** [comment]
If you don't know how to do this, we can make a ne le branch and send another fresh PR that would work

**Comment by richa031** [comment]
ok

**Pull request closed without merging**
