### PR TITLE
added my name to new contributors.md

### PR DESCRIPTION
**Pull request by BrianArchibald**

### CODE REVIEW

**Comment by dipakkr** [comment]
@BrianArchibald thanks for contributing. Please :star: the repo, if you liked it.

**Comment by dipakkr** [comment]
> added myself to new-contributors.md file

You have to send a pull request.

**Comment by albanmahmut** [comment]
> > added myself to new-contributors.md file
> 
> You have to send a pull request.

I actually did. Is it ok now?

**Comment by dipakkr** [comment]
@BrianArchibald please consider adding your introduction as well. You can see how others have added. Thanks !!

**Pull request closed without merging**
