### PR TITLE
Add/php

### PR DESCRIPTION
**Pull request by shauryauppal**
#36

### CODE REVIEW

**Comment by shauryauppal** [comment]
@dipakkr you are checking PR in the wrong way. #32 is supposed to be checked first. It is always bottom to top.

**Comment by dipakkr** [comment]
If you have opened only one PR for the resources or individual PR for individual resources. But you have opened as whole as well as for indiviidual PR. There should not be any bottom or top approach while merging that the benefit of git. 

However don't worry I will merge it by tonight.

**Comment by shauryauppal** [comment]
My bad, I am new to open source. Please verify should the approach be:

from master branch
git checkout -b added/abc

git checkout master

git checkout -b added/xyz

I am not sure, should this be the approach?

**Comment by shauryauppal** [comment]
master to added/abc
then 
master to added/xyz

**Comment by dipakkr** [comment]
Yes, suppose you want to make add two resources with two pr.

Steps 
1. Pull the repository from Github
2. Make branch 1 from master for resource 1 and make a pull request.
3. Switch to master (without merging your resource 1 commit) make new branch and add resources and make pull request. 
4. Switch to master.

With this approach, even your PR is merged in any order it's not going to be a problem or merge conflit.

**Comment by shauryauppal** [comment]
Conclusion: I learned to do PR in the correct manner and wasted my few hours doing it in the wrong way. 

#Hacktoberfest_Learning :

**Pull request closed without merging**
