### PR TITLE
Add Call for Code 2019 details.

### PR DESCRIPTION
**Pull request by krook**
Added the new Call for Code competition links.

### CODE REVIEW

**Comment by dipakkr** [comment]
Hi, @krook sorry for the late update !! It's really great to see the impact #CallForCode have made in the developer community. I will make sure to update schedule for 2020. Thanks! :smile:

**Comment by krook** [comment]
Wonderful, thank you @dipakkr!

**Comment by AAMetatron** [comment]
A-acceptance B-because C-see D-dude E-expected F-friend G-God H-human I -i J-jezus K-k L-love M-man N-now O-original P-please Q-q R-real S-soul T- true U-u V-victorious

**Comment by AAMetatron** [comment]
Lets talk

**Comment by AAMetatron** [comment]
Himitzu

**Pull request merged**
