### PR TITLE
Update README.md with Git and Go

### PR DESCRIPTION
**Pull request by Athul-CA**

### CODE REVIEW

**Comment by dipakkr** [comment]
@Athul-CA update the index of Go language as well in the coding resource.

**Comment by Athul-CA** [comment]
Did it

**Comment by Athul-CA** [comment]
Okay.... I will fork once again as mine is an old fork... Kind Regards,      Athul Cyriac Ajay -------- Original Message --------Subject: Re: [dipakkr/A-to-Z-Resources-for-Students] Update README.md with Git and Go (#1026)From: Deepak Kumar To: dipakkr/A-to-Z-Resources-for-Students CC: Athul Cyriac Ajay ,Mention @dipakkr requested changes on this pull request.

@Athul-CA there are some conflicts in your files. please update your PR as well.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dipakkr/A-to-Z-Resources-for-Students","title":"dipakkr/A-to-Z-Resources-for-Students","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dipakkr/A-to-Z-Resources-for-Students"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dipakkr requested changes on #1026"}],"action":{"name":"View Pull Request","url":"https://github.com/dipakkr/A-to-Z-Resources-for-Students/pull/1026#pullrequestreview-170379800"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dipakkr/A-to-Z-Resources-for-Students/pull/1026#pullrequestreview-170379800",
"url": "https://github.com/dipakkr/A-to-Z-Resources-for-Students/pull/1026#pullrequestreview-170379800",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "@dipakkr requested changes on 1026",
"sections": [
{
"text": "@Athul-CA there are some conflicts in your files. please update your PR as well. ",
"activityTitle": "**Deepak Kumar**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@dipakkr",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/dipakkr/A-to-Z-Resources-for-Students/pull/1026#pullrequestreview-170379800"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 403813560\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Athul-CA** [comment]
New PR

**Pull request closed without merging**
