### PR TITLE
Portugueses translation update

### PR DESCRIPTION
**Pull request by phenriqueleao**

### CODE REVIEW

**Comment by dipakkr** [comment]
@milaaraujo and @vncsalencar pls add your review on this.

**Comment by vncsalencar** [comment]
It looks nice, @dipakkr. He added some missing letter punctuations and some translations look more natural to the average Brazilian. For me, it's okay. (I'm a beginner, so I have to ask. Will merging this change my and @milaaraujo 's edits to lines he didn't change? Cause his edits are okay, but only to the lines he changed. Some of the file's lines are outdated to the time he forked it, that is, before our PR's were merged.) Thanks in advance for your response.

**Comment by dipakkr** [comment]
> It looks nice, @dipakkr. He added some missing letter punctuations and some translations look more natural to the average Brazilian. For me, it's okay. (I'm a beginner, so I have to ask. Will merging this change my and @milaaraujo 's edits to lines he didn't change? Cause his edits are okay, but only to the lines he changed. Some of the file's lines are outdated to the time he forked it, that is, before our PR's were merged.) Thanks in advance for your response.

Yeah, He sent his PR before @milaaraujo, but it needed some review. So I didn't merge it.

**Comment by dipakkr** [comment]
@phenriqueleao Can you please update your PR.

**Comment by milaaraujo** [comment]
His changes look good, but he needs to rebase his code!

**Comment by phenriqueleao** [comment]
@dipakkr sure! Done!
Thank you accepting my suggestions!

**Pull request merged**
